### ISSUE TITLE
Time Gate Knight Chase compatibility

### ISSUE THREAD

**Issue by arnaud33200** [tigrouind/AITD-roomviewer#6]
Thanks a lot for this tools!
I was wondering if it would be easy to setup for another game called Knight's Chase?

I talked with one developer of this game, he said it's the same motor as alone is the dark, the game has the same "ETAGEXX.pak" files.

When I try nothing is display, but I can still change the level (E0R0, E1R0, ...)
The model viewer works for some listbody though

let me know how difficult would it be to adapt this tool to this game, I might be able to help :)

**Comment by tigrouind** [comment]
Hello,

Time Gate: Knight's Chase use indeed exact same format as the previous games. Main difference is that all rooms of a given floor are in individual files instead of being concatenated in a single one. Same for cameras. I have adapted room viewer as it was fairly easy. All you have is to extract "CAMSALXX.pak" and "ETAGEXX.pak" files.

Link to DOSBox is not supported. It _should_ not be difficult to do (unless the way actors are implemented is different from the previous games). What is needed is to find the address in the game executable where the actors array is located. I won't do it but I can give some hints if you are interested.

May I ask you why you want to have support for this particular game ?

**Comment by arnaud33200** [comment]
Amazing! and you already push a commit for this game, thanks a lot!
Being able to link to the DosBox would be a plus, there is no hurry for this feature, let me know when you find something. I look a bit of the code and I could run it, I will take a look if I can find something.

Sure! I'm actually working on a speedrun of this game, I'm using your tools to find some glitch / secret to improve the run. If you want to take a look at my last run, check here: https://youtu.be/2hrdoq2LukQ

**Comment by arnaud33200** [comment]
Also I could get in touch with the game developer!
I can ask them about the actors array.
I'm interested for some hints too, it might be useful since I found a way to go out of boundaries

**Comment by arnaud33200** [comment]
Not priority but I found an exception error with the ModelViewer:
```
UnityException: unknown primitive 10 at 2265
ModelLoader.LoadBody (Boolean resetcamera) (at Assets/Scripts/Model/ModelLoader.cs:394)
ModelLoader.LoadModels (System.String foldername) (at Assets/Scripts/Model/ModelLoader.cs:708)
ModelLoader.Start () (at Assets/Scripts/Model/ModelLoader.cs:668)
```

and also this one:
```
NullReferenceException: Object reference not set to an instance of an object
ModelLoader.UpdateGradientsUVs () (at Assets/Scripts/Model/ModelLoader.cs:1012)
ModelLoader.Update () (at Assets/Scripts/Model/ModelLoader.cs:869)
```

**Comment by tigrouind** [comment]
I have been able to figure out how to parse models.

What is new is 3 types of primitives (8, 9 and 10). It is simply 3D triangles (previous games use convex polygons). It support UV mapping (for textures) and normals (for shading).

I had it almost already working at the time you wrote your last message, but without textures (this part was tricky). If you want to give it a try, make sure you unpack TEXTURES.PAK file.
Animations seems to works (no changes were needed).

**Comment by arnaud33200** [comment]
Thanks, I will give a try now!
I'm also working on linking with the dosbox process.
using the debugger, looks like the `psp` variable doesn't have the right value:
```
bool TryGetExeEntryPoint(out int entryPoint) {
	int psp = memory.ReadUnsignedShort(0x0B30) * 16;
	if (psp > 0)
```
any idea for that? also, how did you find the actor array address? did you use the software Cheat Engine?

**Comment by tigrouind** [comment]
The method you mention is used to know where the game executable is located in DOSBox memory. It does not work here because AFAIK the game use a DOS extender (DOS/4G) and what it return is the address of the extender not the game. What the extender does it to switch the CPU to protected mode to allow the game to address more than 640KB of memory.

About DOSBox : I already made it works (before I saw your message). I said I won't do it a few days ago but temptation was too great. Sorry if you already spent some time on it :(

What I found out: it turns out actors works exactly like in previous games (it's a single array with all actors data). All needed was to find the address of that array.

The way I did it is simple: 
I used a memory scanner (eg: Cheat Engine). Since I know what exact model number the player character use at a given time (thanks to model viewer working correctly) I could just search on that value. Then, I changed player outfit and searched again. After 2-3 searches, I got the address.

It seems that address is pretty much consistent (does not change) between game sessions. Same with different versions of DOSBox. I don't know if that array is dynamically allocated (eg: use malloc() or new) or if it's static. In previous games, it was static. Maybe it's dynamic but ends up at same address "by chance", because the game always allocate things in the same order.

Could you try your side and tell me if it works ? I might not have same game version as you.

**Comment by arnaud33200** [comment]
once again thanks a lot, this is amazing!
I'm gonna try that, I'm super excited, I want to try to exploit a glitch I found to find a big shortcut in the game. I will let you know if I need help with it.

Btw, have you take a look at the speedrun?

**Comment by arnaud33200** [comment]
I've tried searching for the actor address using Cheat Engine, but I might do something wrong. when I think I found the address, from Cheat Engine I have an address that looks like that: `0x0A4A787C` and the value for this address is different from the model number (e.g. `2133755309`). I was wondering if I need to setup something with Cheat Engine? How did end up with the address `0x20542`?

Maybe I didn't attach the right process? I can understand how it works but not so familiar with those tools

![Capture](https://user-images.githubusercontent.com/1728425/84612356-67e6f600-ae8e-11ea-8432-310b42c87ecd.PNG)

**Comment by tigrouind** [comment]
You should use "2 bytes" not "4 bytes" since most fields in the game (at least for actors) are 16-bit. Once you found the address, you have to subtract from it the base address of the memory region that is the closest (go to "View" > "Memory Regions" in Memory viewer of Cheat Engine). Eg: you found `0x0A4A787C`, closest region is `0x0A400000` result is `0xA787C`. That base region address is going to be different for each DOSBox session that is why you have to remove it. The size of that memory region should be close to how much memory is allocated for DOSBox (by default it's 16 MB). The address I have found is [0x3B9000](https://github.com/tigrouind/AITD-roomviewer/blob/3451956ea9760540d9b16e87f9fb29d0e9a2e927/Assets/Scripts/DosBox/DosBox.cs#L663). 

About the run : it's hard for me to appreciate it and understand what is going on as I never played the game (unlike AITD series).

**Comment by arnaud33200** [comment]
Okay i found the address! but it doesn't display right on the viewer, I got a giant green box.
I found 2 address for the model:
```
Base address = 0x0A701000
body address = 0x0AA7A022 ( --> 0x379022)
another body address = 0x0AA9E046 ( --> 0x39D046)
```
I tried to remove to remove 2 since I found this in the the code:
```
box.Body = memory.ReadShort(k + 2);
```

![Capture_wrong_actor](https://user-images.githubusercontent.com/1728425/84669527-f3926e00-aef2-11ea-884c-d32f18dfb58d.PNG)

**Comment by tigrouind** [comment]
I'm confused about why you are searching for that address and trying to make it work.
- Are you having issues with current implementation ? (because you might have a different game version than me)
- Did you maybe misunderstood the fact that Link to DOSBox feature with Time Gate is already implemented and pushed on master branch ?

**Comment by arnaud33200** [comment]
yes I'm aware you push something in master for that, that's what I have locally.
But this `ProcessReader.BaseAddress += 0x3B9000;` doesn't seems to be the right address, as you said, the game version might be different, so now i'm trying to search for the address. So yeah I'm having issue to make it work

**Comment by tigrouind** [comment]
Can you try to add or remove 32 bytes (20 in hexadecimal) to the addresses you found ?

**Comment by arnaud33200** [comment]
okay it works! I remove 34 bytes from `0x379022`.
Thanks :D

**Comment by arnaud33200** [comment]
Do you think it's worth it to put this in the code? something that will try both address until it's good?
I'm having fun with the viewer now, thanks a lot, I will make a video this afternoon

**Comment by tigrouind** [comment]
What I found out so far : 

- game version you use and mine are exactly the same. Executables are binary equal.

- the difference is the DOSBox version. Depending version (eg: DOSBox 0.74 vs SVN Daum), memory blocks allocated in the upper memory (>1MB) using EMS or XMS ends up at different addresses. This is because DOSBox pre-allocate some EMS memory at startup for VCPI. Size seems to be 128KB or 384KB. This is about 256KB difference (same difference as addresses we found for actor array). 

- the actor array is dynamically allocated. I have been able to find the pointer to that array. The pointer is in the executable data segment (there is where all global variables of a program are located). Data segment has a fix address but it is [relocated](https://en.wikipedia.org/wiki/Relocation_(computing)) at runtime by exe loader. Just like actor array itself, the data segment will end up at different addresses depending DOSBox version.

**Comment by arnaud33200** [comment]
I see, that wouldn't be ideal to list address for different version I guess.
mmmmh, that's unfortunate, the only thing I'm thinking about is maybe an input field for the user to write the address of actor model, it can be detailed in the README

**Comment by tigrouind** [comment]
The solution I came with is to locate data segment by searching on a specific pattern.
The data segment contains specific strings so it's easy.
Once I know the where data segment is, I can use the pointer to directly get the actor array address.
It works regardless DOXBox version.  Here is related [commit](https://github.com/tigrouind/AITD-roomviewer/blob/d69336912f629f6d421d9ff794dafee658012e47/Assets/Scripts/DosBox/DosBox.cs#L725).  Some value is subtracted from data segment address because this is the offset where the magic string start in data segment.

**Comment by arnaud33200** [comment]
This is awesome, you did a great job!
I tried, it works on my machine. 
only the texture fix is missing but I don't really need the model viewer, I guess we can close this issue?
